import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/my_components/navbar";
import Footer from "@/components/my_components/footer";
import FloatingBot from "@/components/my_components/FloatingBot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta", // Crea una variabile CSS
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TasteBoard",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {/* Aggiungiamo un main per gestire lo spazio se necessario, 
            ma la Navbar è fixed quindi il contenuto parte da top: 0 */}
      <main className="grow" style={{ paddingTop: "calc(var(--beta-h, 0px) + 5rem)" }}>
        {children}
        <FloatingBot />
      </main>
      <Footer />
    </>
  );
}
