import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jakarta = Plus_Jakarta_Sans({ 
  subsets: ["latin"],
  variable: "--font-jakarta", // Crea una variabile CSS
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TasteBoard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // 1. Mantieni le variabili qui
      className={`${jakarta.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 2. Applica 'font-sans' qui per attivare Jakarta su tutto il progetto */}
      <body className="min-h-full flex flex-col font-sans ">
        {children}
      </body>
    </html>
  );
}

